#mongodb+srv://turkcell-mongodb:<password>@cluster0.z6jqu1l.mongodb.net/?retryWrites=true&w=majority
spring:
  application:
    name: FILTER-SERVICE
  cloud:
    config:
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888