spring:
  application:
    name: discovery-server
  cloud:
    config:
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"